from .storage import StorageContract
from .access_manager import AccessManagerContract

__all__ = ['StorageContract', 'AccessManagerContract']

# Make contracts and ABI/Bytecode accessible (example)
# from .storage import StorageContract, storage_abi, storage_bytecode
# from .access_manager import AccessManagerContract, access_manager_abi, access_manager_bytecode

# You might want to define ABI/Bytecode constants here directly
# or load them from JSON files if generated by tools like Hardhat/Truffle

# Example placeholder:
# storage_abi = [...]
# storage_bytecode = "0x..."
# access_manager_abi = [...]
# access_manager_bytecode = "0x..." 