# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ipcnodeapi_pb2 as ipcnodeapi__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ipcnodeapi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IPCNodeAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectionParams = channel.unary_unary(
                '/ipcnodeapi.IPCNodeAPI/ConnectionParams',
                request_serializer=ipcnodeapi__pb2.ConnectionParamsRequest.SerializeToString,
                response_deserializer=ipcnodeapi__pb2.ConnectionParamsResponse.FromString,
                _registered_method=True)
        self.BucketCreate = channel.unary_unary(
                '/ipcnodeapi.IPCNodeAPI/BucketCreate',
                request_serializer=ipcnodeapi__pb2.IPCBucketCreateRequest.SerializeToString,
                response_deserializer=ipcnodeapi__pb2.IPCBucketCreateResponse.FromString,
                _registered_method=True)
        self.BucketView = channel.unary_unary(
                '/ipcnodeapi.IPCNodeAPI/BucketView',
                request_serializer=ipcnodeapi__pb2.IPCBucketViewRequest.SerializeToString,
                response_deserializer=ipcnodeapi__pb2.IPCBucketViewResponse.FromString,
                _registered_method=True)
        self.BucketList = channel.unary_unary(
                '/ipcnodeapi.IPCNodeAPI/BucketList',
                request_serializer=ipcnodeapi__pb2.IPCBucketListRequest.SerializeToString,
                response_deserializer=ipcnodeapi__pb2.IPCBucketListResponse.FromString,
                _registered_method=True)
        self.BucketDelete = channel.unary_unary(
                '/ipcnodeapi.IPCNodeAPI/BucketDelete',
                request_serializer=ipcnodeapi__pb2.IPCBucketDeleteRequest.SerializeToString,
                response_deserializer=ipcnodeapi__pb2.IPCBucketDeleteResponse.FromString,
                _registered_method=True)
        self.FileUploadChunkCreate = channel.unary_unary(
                '/ipcnodeapi.IPCNodeAPI/FileUploadChunkCreate',
                request_serializer=ipcnodeapi__pb2.IPCFileUploadChunkCreateRequest.SerializeToString,
                response_deserializer=ipcnodeapi__pb2.IPCFileUploadChunkCreateResponse.FromString,
                _registered_method=True)
        self.FileUploadBlock = channel.stream_unary(
                '/ipcnodeapi.IPCNodeAPI/FileUploadBlock',
                request_serializer=ipcnodeapi__pb2.IPCFileBlockData.SerializeToString,
                response_deserializer=ipcnodeapi__pb2.IPCFileUploadBlockResponse.FromString,
                _registered_method=True)
        self.FileView = channel.unary_unary(
                '/ipcnodeapi.IPCNodeAPI/FileView',
                request_serializer=ipcnodeapi__pb2.IPCFileViewRequest.SerializeToString,
                response_deserializer=ipcnodeapi__pb2.IPCFileViewResponse.FromString,
                _registered_method=True)
        self.FileDownloadCreate = channel.unary_unary(
                '/ipcnodeapi.IPCNodeAPI/FileDownloadCreate',
                request_serializer=ipcnodeapi__pb2.IPCFileDownloadCreateRequest.SerializeToString,
                response_deserializer=ipcnodeapi__pb2.IPCFileDownloadCreateResponse.FromString,
                _registered_method=True)
        self.FileDownloadChunkCreate = channel.unary_unary(
                '/ipcnodeapi.IPCNodeAPI/FileDownloadChunkCreate',
                request_serializer=ipcnodeapi__pb2.IPCFileDownloadChunkCreateRequest.SerializeToString,
                response_deserializer=ipcnodeapi__pb2.IPCFileDownloadChunkCreateResponse.FromString,
                _registered_method=True)
        self.FileDownloadBlock = channel.unary_stream(
                '/ipcnodeapi.IPCNodeAPI/FileDownloadBlock',
                request_serializer=ipcnodeapi__pb2.IPCFileDownloadBlockRequest.SerializeToString,
                response_deserializer=ipcnodeapi__pb2.IPCFileBlockData.FromString,
                _registered_method=True)
        self.FileList = channel.unary_unary(
                '/ipcnodeapi.IPCNodeAPI/FileList',
                request_serializer=ipcnodeapi__pb2.IPCFileListRequest.SerializeToString,
                response_deserializer=ipcnodeapi__pb2.IPCFileListResponse.FromString,
                _registered_method=True)
        self.FileDelete = channel.unary_unary(
                '/ipcnodeapi.IPCNodeAPI/FileDelete',
                request_serializer=ipcnodeapi__pb2.IPCFileDeleteRequest.SerializeToString,
                response_deserializer=ipcnodeapi__pb2.IPCFileDeleteResponse.FromString,
                _registered_method=True)


class IPCNodeAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConnectionParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketCreate(self, request, context):
        """Bucket APIs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileUploadChunkCreate(self, request, context):
        """File APIs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileUploadBlock(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileDownloadCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileDownloadChunkCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileDownloadBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IPCNodeAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectionParams': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectionParams,
                    request_deserializer=ipcnodeapi__pb2.ConnectionParamsRequest.FromString,
                    response_serializer=ipcnodeapi__pb2.ConnectionParamsResponse.SerializeToString,
            ),
            'BucketCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketCreate,
                    request_deserializer=ipcnodeapi__pb2.IPCBucketCreateRequest.FromString,
                    response_serializer=ipcnodeapi__pb2.IPCBucketCreateResponse.SerializeToString,
            ),
            'BucketView': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketView,
                    request_deserializer=ipcnodeapi__pb2.IPCBucketViewRequest.FromString,
                    response_serializer=ipcnodeapi__pb2.IPCBucketViewResponse.SerializeToString,
            ),
            'BucketList': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketList,
                    request_deserializer=ipcnodeapi__pb2.IPCBucketListRequest.FromString,
                    response_serializer=ipcnodeapi__pb2.IPCBucketListResponse.SerializeToString,
            ),
            'BucketDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketDelete,
                    request_deserializer=ipcnodeapi__pb2.IPCBucketDeleteRequest.FromString,
                    response_serializer=ipcnodeapi__pb2.IPCBucketDeleteResponse.SerializeToString,
            ),
            'FileUploadChunkCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.FileUploadChunkCreate,
                    request_deserializer=ipcnodeapi__pb2.IPCFileUploadChunkCreateRequest.FromString,
                    response_serializer=ipcnodeapi__pb2.IPCFileUploadChunkCreateResponse.SerializeToString,
            ),
            'FileUploadBlock': grpc.stream_unary_rpc_method_handler(
                    servicer.FileUploadBlock,
                    request_deserializer=ipcnodeapi__pb2.IPCFileBlockData.FromString,
                    response_serializer=ipcnodeapi__pb2.IPCFileUploadBlockResponse.SerializeToString,
            ),
            'FileView': grpc.unary_unary_rpc_method_handler(
                    servicer.FileView,
                    request_deserializer=ipcnodeapi__pb2.IPCFileViewRequest.FromString,
                    response_serializer=ipcnodeapi__pb2.IPCFileViewResponse.SerializeToString,
            ),
            'FileDownloadCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.FileDownloadCreate,
                    request_deserializer=ipcnodeapi__pb2.IPCFileDownloadCreateRequest.FromString,
                    response_serializer=ipcnodeapi__pb2.IPCFileDownloadCreateResponse.SerializeToString,
            ),
            'FileDownloadChunkCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.FileDownloadChunkCreate,
                    request_deserializer=ipcnodeapi__pb2.IPCFileDownloadChunkCreateRequest.FromString,
                    response_serializer=ipcnodeapi__pb2.IPCFileDownloadChunkCreateResponse.SerializeToString,
            ),
            'FileDownloadBlock': grpc.unary_stream_rpc_method_handler(
                    servicer.FileDownloadBlock,
                    request_deserializer=ipcnodeapi__pb2.IPCFileDownloadBlockRequest.FromString,
                    response_serializer=ipcnodeapi__pb2.IPCFileBlockData.SerializeToString,
            ),
            'FileList': grpc.unary_unary_rpc_method_handler(
                    servicer.FileList,
                    request_deserializer=ipcnodeapi__pb2.IPCFileListRequest.FromString,
                    response_serializer=ipcnodeapi__pb2.IPCFileListResponse.SerializeToString,
            ),
            'FileDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.FileDelete,
                    request_deserializer=ipcnodeapi__pb2.IPCFileDeleteRequest.FromString,
                    response_serializer=ipcnodeapi__pb2.IPCFileDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ipcnodeapi.IPCNodeAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ipcnodeapi.IPCNodeAPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IPCNodeAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConnectionParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipcnodeapi.IPCNodeAPI/ConnectionParams',
            ipcnodeapi__pb2.ConnectionParamsRequest.SerializeToString,
            ipcnodeapi__pb2.ConnectionParamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BucketCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipcnodeapi.IPCNodeAPI/BucketCreate',
            ipcnodeapi__pb2.IPCBucketCreateRequest.SerializeToString,
            ipcnodeapi__pb2.IPCBucketCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BucketView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipcnodeapi.IPCNodeAPI/BucketView',
            ipcnodeapi__pb2.IPCBucketViewRequest.SerializeToString,
            ipcnodeapi__pb2.IPCBucketViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BucketList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipcnodeapi.IPCNodeAPI/BucketList',
            ipcnodeapi__pb2.IPCBucketListRequest.SerializeToString,
            ipcnodeapi__pb2.IPCBucketListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BucketDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipcnodeapi.IPCNodeAPI/BucketDelete',
            ipcnodeapi__pb2.IPCBucketDeleteRequest.SerializeToString,
            ipcnodeapi__pb2.IPCBucketDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileUploadChunkCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipcnodeapi.IPCNodeAPI/FileUploadChunkCreate',
            ipcnodeapi__pb2.IPCFileUploadChunkCreateRequest.SerializeToString,
            ipcnodeapi__pb2.IPCFileUploadChunkCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileUploadBlock(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ipcnodeapi.IPCNodeAPI/FileUploadBlock',
            ipcnodeapi__pb2.IPCFileBlockData.SerializeToString,
            ipcnodeapi__pb2.IPCFileUploadBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipcnodeapi.IPCNodeAPI/FileView',
            ipcnodeapi__pb2.IPCFileViewRequest.SerializeToString,
            ipcnodeapi__pb2.IPCFileViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileDownloadCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipcnodeapi.IPCNodeAPI/FileDownloadCreate',
            ipcnodeapi__pb2.IPCFileDownloadCreateRequest.SerializeToString,
            ipcnodeapi__pb2.IPCFileDownloadCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileDownloadChunkCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipcnodeapi.IPCNodeAPI/FileDownloadChunkCreate',
            ipcnodeapi__pb2.IPCFileDownloadChunkCreateRequest.SerializeToString,
            ipcnodeapi__pb2.IPCFileDownloadChunkCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileDownloadBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ipcnodeapi.IPCNodeAPI/FileDownloadBlock',
            ipcnodeapi__pb2.IPCFileDownloadBlockRequest.SerializeToString,
            ipcnodeapi__pb2.IPCFileBlockData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipcnodeapi.IPCNodeAPI/FileList',
            ipcnodeapi__pb2.IPCFileListRequest.SerializeToString,
            ipcnodeapi__pb2.IPCFileListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FileDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ipcnodeapi.IPCNodeAPI/FileDelete',
            ipcnodeapi__pb2.IPCFileDeleteRequest.SerializeToString,
            ipcnodeapi__pb2.IPCFileDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
